version: "3.8"

services:
  postgres:
      image: postgres:14-alpine
      container_name: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_NAME: postgres
      volumes:
        - "referral_system_django:/var/lib/postgresql/data"
  app:
    build:
      dockerfile: deploy/Dockerfile
      context: ..
    depends_on:
      - postgres
    ports:
      - 80:80
    command: bash -c "./deploy/wait-for-it.sh postgres:5432 &&
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:80"
    environment:
      DB_PORT: 5432
      DB_HOST: postgres
    restart: always

volumes:
  referral_system_django: