# Generated by Django 5.0.4 on 2024-04-21 15:56

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invite_code",
            field=models.CharField(
                default=user.models.get_invite_code, max_length=6, unique=True
            ),
        ),
    ]
