# Generated by Django 5.0.4 on 2024-04-21 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_invite_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referee_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
