# Generated by Django 5.0.4 on 2024-04-22 16:40

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_referrer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=12,
                region=None,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(12)],
            ),
        ),
    ]
